name: Hutool CI

on:
  workflow_dispatch:
  push:
    branches:
      - v5-master

permissions: write-all

jobs:
  build_application:
    name: Compile with JDK 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: 8

      - name: Build Maven Application
        shell: bash
        run: mvn -U -B -fae -DskipTests clean install

      - name: Create SBOM For hutool-all
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./hutool-all/target/
          artifact-name: hutool-all-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Tar Maven Build Repository
        shell: bash
        run: tar -czf maven-build.tgz -C ~ .m2/repository

      - name: Upload Maven Build Repository
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: maven-build.tgz

      - name: Generate Maven Dependency Tree
        shell: bash
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt

      - name: Create Maven Dependency Tree Zip File
        shell: bash
        run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r mvn-dependency-tree.zip {} +

      - name: Upload Maven Dependency Tree Zip
        uses: actions/upload-artifact@v4
        with:
          name: maven-dependency-tree
          path: mvn-dependency-tree.zip

  run_sca_scanning:
    needs: [ build_application ]
    name: Run SCA Scanning Workflow
    uses: seansmith39/H6060-Experiment-Workflows/.github/workflows/experiment_1_sca_mvn.yml@v1.0.5
    secrets: inherit
    with:
      project-name: hutool
      java-version: 8
      java-distribution: adopt
      mvn-build-artifact: maven-build
      snyk-sarif-enabled: false

  run_sast_scanning:
    needs: [ build_application ]
    name: Run SAST Scanning Workflow
    uses: seansmith39/H6060-Experiment-Workflows/.github/workflows/experiment_1_sast_mvn.yml@v1.0.5
    secrets: inherit
    with:
      sonarqube-project-name: H6060-hutool
      mvn-build-command: mvn -U -B -fae -DskipTests clean install
      mvn-jacoco-command: mvn -U -B -fae -DskipTests clean install; mvn test verify
      jacoco-coverage-file: 'hutool-bom/target/site/jacoco-aggregate/jacoco.xml'
